from __future__ import annotations
"""
CyberDrishti AI — Section 65B Evidence Certificate PDF Generator (Phase 7)
Uses Jinja2 + WeasyPrint. Generates the analysis-aid document, explicitly
stating it is NOT a replacement for the device custodian's certificate.
"""
import hashlib
import pathlib
import uuid
from datetime import datetime, timezone

from jinja2 import Environment, FileSystemLoader, select_autoescape
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
try:
    from weasyprint import HTML
except (ImportError, OSError):
    # WeasyPrint depends on native Pango/GObject libraries that are not bundled
    # with Windows Python environments.  ReportLab is a declared pure-Python
    # fallback so report generation remains available for local deployments.
    HTML = None

from config import settings
from db.models import AuditLog, Case, EvidenceFile, Entity, Correlation

REPORT_DIR    = pathlib.Path(settings.report_output_dir)
TEMPLATE_DIR  = pathlib.Path(settings.report_template_dir)
REPORT_DIR.mkdir(parents=True, exist_ok=True)

# Inline HTML template (avoids needing a separate template file for initial setup)
_TEMPLATE_HTML = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<title>Section 65B Evidence Certificate — {{ case.case_number }}</title>
<style>
  body { font-family: 'Arial', sans-serif; font-size: 12px; color: #1a1a2e; margin: 40px; }
  h1 { font-size: 18px; font-weight: bold; text-align: center; margin-bottom: 4px; }
  h2 { font-size: 14px; font-weight: bold; margin-top: 20px; border-bottom: 1px solid #ccc; padding-bottom: 4px; }
  .subtitle { text-align: center; color: #666; margin-bottom: 24px; font-size: 11px; }
  .warning { background: #fff3cd; border: 1px solid #ffc107; padding: 10px; margin-bottom: 20px;
             border-radius: 4px; font-size: 11px; }
  table { width: 100%; border-collapse: collapse; margin-top: 8px; font-size: 11px; }
  th { background: #f0f4f8; font-weight: bold; padding: 6px 8px; border: 1px solid #d0d7de; text-align: left; }
  td { padding: 5px 8px; border: 1px solid #d0d7de; word-break: break-all; }
  tr:nth-child(even) { background: #f8f9fa; }
  .badge { display: inline-block; padding: 2px 6px; border-radius: 12px; font-size: 10px; font-weight: bold; }
  .badge-ok { background: #d1fae5; color: #065f46; }
  .badge-high { background: #fee2e2; color: #991b1b; }
  .badge-med { background: #fef3c7; color: #92400e; }
  .footer { margin-top: 40px; font-size: 10px; color: #888; border-top: 1px solid #eee; padding-top: 8px; }
  .page-break { page-break-before: always; }
</style>
</head>
<body>

<h1>CyberDrishti AI — Investigation Evidence Certificate</h1>
<p class="subtitle">Analysis Aid Document &nbsp;·&nbsp; NOT a replacement for the Section 65B device-custodian certificate</p>

<div class="warning">
  ⚠ <strong>Legal Notice:</strong> This document is generated by an automated analysis tool and constitutes an
  analysis aid only. It does <strong>NOT</strong> satisfy the requirements of Section 65B, Indian Evidence Act / BSA
  Section 63 for admissibility of electronic records. A valid Section 65B certificate must be issued by the
  person who is in charge of and responsible for the computer resource on which the original evidence resides.
</div>

<h2>1. Case Information</h2>
<table>
  <tr><th>Case Number</th><td>{{ case.case_number }}</td><th>Title</th><td>{{ case.title }}</td></tr>
  <tr><th>Crime Type</th><td>{{ case.crime_type or '—' }}</td><th>FIR Number</th><td>{{ case.fir_number or '—' }}</td></tr>
  <tr><th>Police Station</th><td>{{ case.police_station or '—' }}</td><th>Priority</th>
      <td><span class="badge badge-{{ 'high' if case.priority == 'high' else ('med' if case.priority == 'medium' else 'ok') }}">{{ case.priority|upper }}</span></td></tr>
  <tr><th>Status</th><td>{{ case.status|upper }}</td><th>Report Generated</th><td>{{ generated_at }}</td></tr>
</table>

<h2>2. Evidence File SHA-256 Hash Table</h2>
<table>
  <tr><th>#</th><th>Filename</th><th>Type</th><th>Size (bytes)</th><th>Upload Status</th><th>SHA-256 Hash</th></tr>
  {% for f in evidence_files %}
  <tr>
    <td>{{ loop.index }}</td>
    <td>{{ f.original_name }}</td>
    <td>{{ f.file_type|upper }}</td>
    <td>{{ f.file_size_bytes or '—' }}</td>
    <td><span class="badge badge-ok">{{ f.upload_status|upper }}</span></td>
    <td style="font-family:monospace;font-size:9px;">{{ f.sha256_hash }}</td>
  </tr>
  {% else %}
  <tr><td colspan="6" style="text-align:center;color:#888;">No evidence files ingested.</td></tr>
  {% endfor %}
</table>

<h2>3. Extracted Entities ({{ entity_count }} total)</h2>
<table>
  <tr><th>Type</th><th>Canonical Value</th><th>Community</th><th>Bridge Score</th></tr>
  {% for e in entities[:50] %}
  <tr>
    <td><strong>{{ e.entity_type }}</strong></td>
    <td>{{ e.canonical_value }}</td>
    <td>{{ e.community_id if e.community_id is not none else '—' }}</td>
    <td>{{ "%.3f"|format(e.bridge_score or 0) }}</td>
  </tr>
  {% endfor %}
  {% if entity_count > 50 %}<tr><td colspan="4" style="text-align:center;color:#888;">… and {{ entity_count - 50 }} more entities.</td></tr>{% endif %}
</table>

<h2>4. Flagged Hidden Links ({{ link_count }} total)</h2>
<table>
  <tr><th>Entity A</th><th>Entity B</th><th>Score</th><th>Threshold</th><th>Jaccard</th><th>AA</th><th>Temporal</th><th>FinScore</th></tr>
  {% for c in correlations %}
  <tr>
    <td>{{ c.entity_a_value or (c.entity_a_id|string)[:8] }}</td>
    <td>{{ c.entity_b_value or (c.entity_b_id|string)[:8] }}</td>
    <td><strong>{{ "%.4f"|format(c.final_score) }}</strong></td>
    <td>{{ "%.4f"|format(c.threshold) }}</td>
    <td>{{ "%.3f"|format(c.component_scores.get('jaccard', 0)) }}</td>
    <td>{{ "%.3f"|format(c.component_scores.get('adamic_adar_norm', 0)) }}</td>
    <td>{{ "%.3f"|format(c.component_scores.get('temporal_norm', 0)) }}</td>
    <td>{{ "%.3f"|format(c.component_scores.get('fin_score', 0)) }}</td>
  </tr>
  {% else %}
  <tr><td colspan="8" style="text-align:center;color:#888;">No hidden links flagged.</td></tr>
  {% endfor %}
</table>

<div class="page-break"></div>

<h2>5. Audit Log (last {{ audit_entries|length }} entries)</h2>
<table>
  <tr><th>ID</th><th>Timestamp</th><th>Action</th><th>Entry Hash (SHA-256)</th></tr>
  {% for entry in audit_entries %}
  <tr>
    <td>{{ entry.id }}</td>
    <td>{{ entry.event_timestamp.strftime('%Y-%m-%d %H:%M:%S UTC') if entry.event_timestamp else '—' }}</td>
    <td>{{ entry.action }}</td>
    <td style="font-family:monospace;font-size:9px;">{{ entry.entry_hash }}</td>
  </tr>
  {% endfor %}
</table>

<div class="footer">
  Generated by CyberDrishti AI v{{ version }} &nbsp;·&nbsp; {{ generated_at }} UTC &nbsp;·&nbsp;
  This document is an analysis aid. For legal admissibility, obtain a device-custodian certificate
  as per Section 65B, Indian Evidence Act / BSA Section 63.
</div>
</body>
</html>
"""


async def generate_65b_pdf(
    case_id:    str,
    db:         AsyncSession,
    officer_id: str | None = None,
) -> str:
    """
    Generate a Section 65B analysis-aid PDF for the given case.
    Returns the path to the generated PDF file.
    """
    # UUID columns bind via value.hex on SQLite — a raw path string 500s
    # ('str' object has no attribute 'hex'). Coerce once here; AuditLog.resource_id
    # is Text (stores the string form) so that lookup keeps the original string.
    try:
        case_uuid = case_id if isinstance(case_id, uuid.UUID) else uuid.UUID(str(case_id))
    except (ValueError, AttributeError, TypeError):
        raise ValueError(f"Case {case_id} not found")

    # Fetch case
    case = await db.get(Case, case_uuid)
    if not case:
        raise ValueError(f"Case {case_id} not found")

    # Fetch evidence files
    ev_files = (await db.execute(
        select(EvidenceFile).where(EvidenceFile.case_id == case_uuid)
    )).scalars().all()

    # Fetch entities
    entities = (await db.execute(
        select(Entity).where(Entity.case_id == case_uuid)
    )).scalars().all()

    # Fetch flagged correlations
    correlations = (await db.execute(
        select(Correlation).where(
            Correlation.case_id == case_uuid,
            Correlation.decision == "flagged",
        )
    )).scalars().all()

    # Fetch audit entries
    audit_entries = (await db.execute(
        select(AuditLog)
        .where(AuditLog.resource_id == case_id)
        .order_by(AuditLog.id.desc())
        .limit(50)
    )).scalars().all()

    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S")

    # Render HTML
    from jinja2 import Environment
    env  = Environment()
    env.globals["str"] = str
    tmpl = env.from_string(_TEMPLATE_HTML)
    html_content = tmpl.render(
        case=case,
        evidence_files=ev_files,
        entities=entities,
        entity_count=len(entities),
        correlations=correlations,
        link_count=len(correlations),
        audit_entries=audit_entries,
        generated_at=generated_at,
        version="1.0.0",
    )

    # Generate PDF. Prefer the richer HTML rendition where the native
    # WeasyPrint dependencies are present, otherwise use the portable fallback.
    pdf_path = REPORT_DIR / f"65B_{case.case_number.replace('/', '_')}_{case_id[:8]}.pdf"
    if HTML is not None:
        HTML(string=html_content).write_pdf(str(pdf_path))
    else:
        _write_reportlab_pdf(
            pdf_path, case, ev_files, entities, correlations, audit_entries, generated_at
        )

    return str(pdf_path)


def _write_reportlab_pdf(pdf_path, case, evidence_files, entities, correlations, audit_entries, generated_at):
    """Portable Section 65B analysis-aid PDF when WeasyPrint is unavailable."""
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet
    from reportlab.lib.units import mm
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
    from reportlab.lib import colors

    styles = getSampleStyleSheet()
    body = styles["BodyText"]
    story = [
        Paragraph("CyberDrishti AI - Investigation Evidence Certificate", styles["Title"]),
        Paragraph("Analysis aid only; not a replacement for a Section 65B device-custodian certificate.", body),
        Spacer(1, 5 * mm),
        Paragraph("1. Case Information", styles["Heading2"]),
        Table([
            ["Case number", case.case_number, "Status", case.status.upper()],
            ["Title", case.title, "Generated", generated_at],
        ], colWidths=[30 * mm, 65 * mm, 30 * mm, 55 * mm]),
        Spacer(1, 5 * mm),
        Paragraph("2. Evidence File SHA-256 Hash Table", styles["Heading2"]),
    ]
    evidence_rows = [["Filename", "Type", "Status", "SHA-256"]]
    evidence_rows.extend([
        [f.original_name, f.file_type.upper(), f.upload_status.upper(), f.sha256_hash]
        for f in evidence_files
    ] or [["No evidence files ingested.", "", "", ""]])
    story.append(Table(evidence_rows, repeatRows=1, colWidths=[45 * mm, 20 * mm, 25 * mm, 90 * mm]))
    story.extend([Spacer(1, 5 * mm), Paragraph(f"3. Extracted Entities ({len(entities)} total)", styles["Heading2"])])
    entity_rows = [["Type", "Canonical Value", "Bridge Score"]]
    entity_rows.extend([[e.entity_type, e.canonical_value, f"{(e.bridge_score or 0):.3f}"] for e in entities[:50]] or [["No entities extracted.", "", ""]])
    story.append(Table(entity_rows, repeatRows=1, colWidths=[35 * mm, 105 * mm, 30 * mm]))
    story.extend([Spacer(1, 5 * mm), Paragraph(f"4. Flagged Hidden Links ({len(correlations)} total)", styles["Heading2"]), Paragraph(f"Audit entries included: {len(audit_entries)}", body)])
    document = SimpleDocTemplate(str(pdf_path), pagesize=A4, rightMargin=15 * mm, leftMargin=15 * mm)
    for table in (item for item in story if isinstance(item, Table)):
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e8eef6")),
            ("GRID", (0, 0), (-1, -1), 0.25, colors.grey),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
        ]))
    document.build(story)
